### ISSUE TITLE
How to set the custom font for regular text in Swift 3.0

### ISSUE THREAD

**Issue by tarzon** [bmoliveira/MarkdownKit#16]
I am unable to set the custom font for the regular text. My font file only contains a single font style, so it crashes at initialisation of **MarkdownParser** where it is unable to find its corresponding **MarkdownBold** font. Previously in Swift 2.3, it used to use the font set to UILable, but with the update to Swift 3.0, it no longer supports that. Any idea how to support that? Here is how I initialised _MarkdownParser_

`let markdownParser = MarkdownParser(font: UIFont(name: "Some Custom Font Name", size: 16.0))`

**Comment by tarzon** [comment]
Hi @ivanbruel, any update on this issue would be helpful.

**Comment by bmoliveira** [comment]
I've just added a font on the example project with only the regular definition and its working, if the problem still persists, please reopen the issue.

Thank you
