### ISSUE TITLE
Code interpreted incorrectly

### ISSUE THREAD

**Issue by kirankunigiri** [bmoliveira/MarkdownKit#21]
<img width="1180" alt="screen shot 2017-06-22 at 10 19 38 am" src="https://user-images.githubusercontent.com/9154932/27447049-67d44500-5734-11e7-8db4-df39cb70c577.png">

The code text is replaced by numbers.

**Comment by DavidLari** [comment]
I have a fork that fixes that and a couple of other issues. https://github.com/DavidLari/MarkdownKit

**Comment by bmoliveira** [comment]
PR already merged, it should be fixed on next release.
