### ISSUE TITLE
wrong regex

### ISSUE THREAD

**Issue by vzarubanov** [bmoliveira/MarkdownKit#23]
MarkdownBold does not work for `"(**BOLD**)"` string, but works for `"( **BOLD**)"`

fixed by using custom element:

```
class MarkdownWorkingBold: MarkdownBold {
    
    private static let regex = "(\\s+|^|\\B)(\\*\\*|__)(.+?)(\\2)"
    
    override var regex: String {
        return MarkdownWorkingBold.regex
    }
}
```

**Comment by DavidLari** [comment]
Since the maintainer has not responded, I have cloned and renamed this project, and merged most of the outstanding PRs manually. New PRs are welcomed as well.  https://github.com/davidlari/Haring
