### ISSUE TITLE
Abandoned????

### ISSUE THREAD

**Issue by DavidLari** [bmoliveira/MarkdownKit#30]
Since the maintainer appears to have abandoned this, I have cloned and renamed this project, and merged most of the outstanding PRs manually. I also support Swift 4. New PRs are welcomed as well.  https://github.com/davidlari/Haring

**Comment by Coeur** [comment]
@bmoliveira woah, welcome back, Bruno!

**Comment by bmoliveira** [comment]
Thank you, is good to be back!
