### ISSUE TITLE
Crash in `String+UTF16.swift` - `unescapeUTF16()`

### ISSUE THREAD

**Issue by Frederiks96** [bmoliveira/MarkdownKit#35]
I have experienced a crash in the `unescapeUTF16` method in `String+UTF16.swift`. The markdown that led to the crash can be found here: https://github.com/apple/swift-evolution/blob/master/proposals/0240-ordered-collection-diffing.md

The crash was found on the line `let endIndex = index(self.startIndex, offsetBy: $0 + 4)` in the following code snippet:
```
stride(from: 0, to: count, by: 4).forEach {
    let startIndex = index(self.startIndex, offsetBy: $0)
    let endIndex = index(self.startIndex, offsetBy: $0 + 4)
    let hex4 = String(self[startIndex..<endIndex])
    if let utf16 = UInt16(hex4, radix: 16) {
        utf16Array.append(utf16)
    }
}
```

**Comment by DavidLari** [comment]
On a fork of this project called Haring, we fixed this issue by adding the following line to the beginning of the function. It stops the crash, but perhaps there's a better fix.

```
guard count >= 4 else { return nil }
```

**Comment by bmoliveira** [comment]
This crash should not be happening anymore. 

But the code Element parser is not working 100% according to the Github parser if the language is specified it will appear on the final view and it shouldn't. 

Check out #37 for more information.
