### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by kardeslik** [bmoliveira/MarkdownKit#38]
Hey,

Do you plan to add macOS support?

**Comment by bmoliveira** [comment]
Hey,

In the 1.5 version that I've just deployed it should be working!

Can you please try it out?

Thanks

**Comment by kardeslik** [comment]
Yeah it's working, thanks! 

Is there any specific reason for setting bundle/module name as `MarkdownKit_osx`?
It'd be better if it's just `MarkdownKit`, imo.

**Comment by mischa-hildebrand** [comment]
✅ Works for me on macOS. @bmoliveira, I think you can close this issue.

**Comment by bmoliveira** [comment]
Closing this as it is working for osx and opened a new issue for renaming purposes.
