### ISSUE TITLE
Combined bold and italic formatting doesn't work as expected.

### ISSUE THREAD

**Issue by mischa-hildebrand** [bmoliveira/MarkdownKit#39]
First of all: Awesome framework, thank you for open-sourcing it! 👍

---

When nesting emphasis and strong delimiters (i.e. **bold** and _italic_ delimiters) as follows:

    _**word**_

I would expect `word` to be formatted both **bold** and _italic_:

> _**word**_

This is specified in the [CommonMark Spec](https://spec.commonmark.org/0.28/#emphasis-and-strong-emphasis) and as you can see above, it's also the default behavior on GitHub.

The _MarkdownKit_ parser currently formats the Markdown input above as only italic:

> _word_

I would suggest to change the parser's behavior according to the specification.

**Comment by bmoliveira** [comment]
I noticed the problem, but currently, I couldn't find a bit to work on it. Is this critical to you at the moment?

**Comment by mischa-hildebrand** [comment]
No, it's not critical. I've been working on a Markdown parser myself and tried some existing frameworks, including _MarkdownKit_. I think it's not straight forward – especially the nesting part (and the wrong syntax correction) specified in _CommonMark_ is difficult to achieve while maintaining simplicity and a good code structure at the same time.

Right now, your code looks neat because there is a 1:1 mapping to a specific font style for every element. It doesn't allow to add a new trait (like italic) to an existing trait (like boldface). Thus, allowing nested formatting and syntax fixes has some bigger implications to the architecture of the framework.

**Comment by nodediggity** [comment]
+1

**Comment by bmoliveira** [comment]
I know this issue isn't easy or quick to fix, and I, unfortunately, don't have much time at the moment to work on it, but if you guys want to start the greatest revamp of all of this lib let's do it.

**Comment by gaebel** [comment]
This has been fixed by @velga. It will be in the next release.
