### ISSUE TITLE
Is there a version built with the Swift 5.0 compiler?

### ISSUE THREAD

**Issue by janely-jhh** [bmoliveira/MarkdownKit#47]
We are looking for a solution that will work with Xcode 10.2. Thanks!

**Comment by Lweek** [comment]
@janely-jhh Check out pull requests. You can pull that version before it will be officially merged.

**Comment by janely-jhh** [comment]
Appreciate the quick response. We use Carthage. How would I reference that in a Cartfile?

**Comment by Lweek** [comment]
@janely-jhh 
Check out this article. Search for "The Cartfile Format".
https://www.raywenderlich.com/416-carthage-tutorial-getting-started
