### ISSUE TITLE
Links without explicit schemes formatted but not working

### ISSUE THREAD

**Issue by rberggreen** [bmoliveira/MarkdownKit#58]
**Steps to reproduce**
1. Parse a markdown text containing links without explicit schemes:

```swift
let markdownParser = MarkdownParser()
let markdown = """
    Link with implicit scheme: old.reddit.com
    Link with explicit scheme: https://old.reddit.com/
    """
textView.attributedText = markdownParser.parse(markdown)
```

2. Observe that the link with the implicit scheme is formatted as a link
3. Select the link

**Expected behaviour**
Either the link is opened in Safari,
or the text is not formatted as a link at all

**Actual behaviour**
* The link is formatted as a link
* Selecting the link does nothing
* Printed to console: `Could not find any actions for URL old.reddit.com without any result.`

My suggestion would be to have an option for a default scheme for links that is added if the scheme is nil.

**Comment by kboirel** [comment]
I have the same problem...

**Comment by gaebel** [comment]
I like the idea with a default scheme, I'll add this to #90.
