### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by Drusy** [bmoliveira/MarkdownKit#59]
Since Xcode 11 includes Swift Package Manager, it would be nice to support it

**Comment by OscarGorog** [comment]
See #60

**Comment by OscarGorog** [comment]
Just needs to be approved now... @bmoliveira?

**Comment by diniska** [comment]
One more pull request for Swift Package Manager: https://github.com/bmoliveira/MarkdownKit/pull/68

**Comment by aloveric** [comment]
+1

**Comment by gaebel** [comment]
We've just published a new release with SPM support
