### ISSUE TITLE
App crash on link markdown

### ISSUE THREAD

**Issue by victormihaita** [bmoliveira/MarkdownKit#66]
The app is crashing on this format of link: 
`[(William) Davenport Griffen](/artists/(william)-davenport-griffen)`

The issue is with the name William in brackets. It seems that the framework treats (William) as a separate link.. instead of just a plain text. 
The app is crashing in the `MarkdownLink.swift` file on `formatText` function.

@bmoliveira

**Comment by josjevv** [comment]
I think I fixed this issue (haven't tested your example though). Since no PRs seem to be merged here, you can use our fork: https://github.com/SocialSchools/MarkdownKit (version 1.7.1)

**Comment by gaebel** [comment]
@josjevv Your regex works perfectly, I've implemented it in #90. I'll publish a new release in the next few days.

**Comment by josjevv** [comment]
awesome, thanks for bringing it to the main project.
