### ISSUE TITLE
Color of "regular" text

### ISSUE THREAD

**Issue by ogezue** [bmoliveira/MarkdownKit#7]
In my case I have this string that is displayed as a button label.
`"Already registered? **Login**"`

```
       let parser = MarkdownParser(font: UIFont.systemFont(ofSize: 17))
        parser.automaticLinkDetectionEnabled = false
        parser.bold.color = UIColor.white
        parser.header.color = UIColor.white
```

My problem is that "Already registered?" is displayed in blue and "Login" is white as set by bold-attribute. How can the color for regular text be set? Why is it set to blue?

**Comment by ivanbruel** [comment]
Blue is most likely either your button's tintColor or your button's textLabel textColor.
With that said, might make sense to configure the default color on MarkdownKit.
Keeping this open for now.

**Comment by ogezue** [comment]
Yes - it was the tint-color. I used MardownKit before and there the color can be set in the parser. It would be great if you can adopt it.

**Comment by chrisdhaan** [comment]
👍 this would be a great feature addition

**Comment by DavidLari** [comment]
+1 to adding color property for regular text.

**Comment by ikunin** [comment]
Hi, guys, 

I vote with all my hands and fingers for this feature. It would be awesome if you could add it. 

Thanks in advance and greetings from Berlin

**Comment by kajensen** [comment]
Hi guys, added a PR for this. Just set the color like you would the font, when initializing the parser.

**Comment by bmoliveira** [comment]
I've already merged the PR with the setting of text colour, I think it should solve the issue. If still persists please re-open the issue.
