### ISSUE TITLE
Errors occur when installing via Swift Package Manager

### ISSUE THREAD

**Issue by jordanhbuiltbyhq** [bmoliveira/MarkdownKit#82]
If you go to File > Swift Packages > Add Package Dependency, paste in https://github.com/bmoliveira/MarkdownKit.git, click Next, leave it at the default up to 1.4.1 rule, click Next, you'll get an error stating:
> https://github.com/bmoliveira/MarkdownKit.git has no Package.swift manifest for version 1.4.1 in https://github.com/bmoliveira/MarkdownKit.git

If you instead put in 1.7.0 as is implied in the Readme, you'll get an error stating:
> Dependencies could not be resolved because no versions of 'MarkdownKit' match the requirement 1.7.0..<2.0.0 and root depends on 'MarkdownKit' 1.7.0..<2.0.0.

<img width="842" alt="Screen Shot 2021-03-22 at 1 33 50 PM" src="https://user-images.githubusercontent.com/15804476/112048290-dd65ae00-8b13-11eb-800d-22db28873daf.png">

**Comment by gaebel** [comment]
There is currently no release with the SPM integration. For now select master as branch instead of the version when adding the package to your project. Sorry for the misleading version number in the Readme. We'll create the release in the next few days.

**Comment by gaebel** [comment]
We've just published the release
