### ISSUE TITLE
Carthage Install Failing

### ISSUE THREAD

**Issue by tjolsen-vn** [bmoliveira/MarkdownKit#84]
I'm trying to install via Carthage on Xcode 12.2 and keep getting this error:
```
*** Building scheme "MarkdownKit-AppKit" in MarkdownKit.xcworkspace
*** Building scheme "MarkdownKit" in MarkdownKit.xcworkspace
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Users/tj/Library/Caches/org.carthage.CarthageKit/DerivedData/12.2_12B45b/MarkdownKit/1.7.0/Build/Intermediates.noindex/ArchiveIntermediates/MarkdownKit/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/MarkdownKit.framework/MarkdownKit /Users/tj/Library/Caches/org.carthage.CarthageKit/DerivedData/12.2_12B45b/MarkdownKit/1.7.0/Build/Products/Release-iphonesimulator/MarkdownKit.framework/MarkdownKit -output /Volumes/VNStorage/Repos/iosSwitchbacks/switchbacks-ios/Carthage/Build/iOS/MarkdownKit.framework/MarkdownKit

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/yt/zk5_9dxd08b_4gpddjpl6qx00000gn/T/carthage-xcodebuild.RtHQE3.log
```

Is this because Xcode 12.2 (Swift 5.3.1) is not supported? Or maybe `arm64` architecture needs to be excluded?

**Comment by gaebel** [comment]
Excluding `arm64` for the simulator should work, but  the preferred way with Xcode 12 is to build platform independent XCFrameworks.
Run `brew upgrade carthage` to get the latest version of Carthage.
Then delete your Carthage/build folder and run `carthage update --use-xcframeworks`. Afterwards link the generated MarkdownKit.xcframework or MarkdownKit_osx.xcframework.

**Comment by tjolsen-vn** [comment]
Awesome, thanks. I can do that. I'm also able to get it to work with another bash script. Thanks for the info!
