### ISSUE TITLE
Combination of italic with custom markdown element not working

### ISSUE THREAD

**Issue by S2V** [bmoliveira/MarkdownKit#97]
Reproducible for the case when text has mixed text-decoration style with custom markdown element. In my case. I have the custom element that not supports by markdown be default - underline(++). I implement the custom markdown element for parsing (like MarkdownStrikethrough).
```swift
class MarkdownUnderline: MarkdownCommonElement {
	
	var font: MarkdownFont?
	var color: MarkdownColor?
	
	private static let regex = "(.?|^)(\\+\\+)(?=\\S)(.+?)(?<=\\S)(\\2)"

	var regex: String {
		return MarkdownUnderline.regex
	}
	
	public init(font: MarkdownFont?, color: MarkdownColor? = nil) {
		self.font = font
		self.color = color
	}
	
	public func match(_ match: NSTextCheckingResult, attributedString: NSMutableAttributedString) {
		attributedString.deleteCharacters(in: match.range(at: 4))

		var attributes = attributedString.attributes(
			at: match.range(at: 3).location,
			longestEffectiveRange: nil,
			in: match.range(at: 3)
		)

		attributes[.underlineStyle] = NSNumber.init(value: NSUnderlineStyle.single.rawValue)

		attributedString.addAttributes(attributes, range: match.range(at: 3))

		attributedString.deleteCharacters(in: match.range(at: 2))
	}
}
```
But parsing result is not correct, for example for text `**_++Lorem ipsum++_**` will be produced the attributed text:
![image](https://user-images.githubusercontent.com/5613351/130200002-f2bb6dc4-12bd-4503-8f7a-652761fdc0f4.png)

`_++Lorem ipsum++_`
![image](https://user-images.githubusercontent.com/5613351/130200298-083532c3-3ccd-4f76-8bc7-d008dc0f5c0a.png)

If I change the regex to `(.?|^)(\\*|_)(?=\\S)(.+?)(?<=\\S)(\\2)` ,that was implemented for [fix](https://github.com/bmoliveira/MarkdownKit/issues/73), the parsing result is correct.

**Comment by gaebel** [comment]
I tried parsing with your custom element and it works fine. The last merged PRs haven't been published yet, though. Do you possibly use the latest version (1.7.1)? If yes, could you check if switching to the `master` branch fixes your issue?

**Comment by S2V** [comment]
@gaebel Yep, you are right. I provided a not correct example, sorry - that is my bad. If be more correct  - parsing result for  `**_  Lorem ipsum  _**` is correct, but if you change the order of applying the styles to `++_**Lorem ipsum**_++` - result will be not correct. 
Test text:
```swift
let test = """
 ++_**Mixed U/I/B Cras non erat dolor. In euismod laoreet iaculis. Aliquam viverra rutrum dui, at volutpat orci tempus et.**_++

 **_++Mixed B/I/U Cras non erat dolor. In euismod laoreet iaculis. Aliquam viverra rutrum dui, at volutpat orci tempus et.++_**
"""
```
Result `1.7.1`:
![image](https://user-images.githubusercontent.com/5613351/130225877-71b42d0f-03bf-434a-9a5f-1e78393cd25f.png)


Result `master: 072e192`:
![image](https://user-images.githubusercontent.com/5613351/130224515-1ee3a530-7327-4e2f-8953-e823c3854746.png)

Result `master: 072e192` + modified regex for italic element to`(.?|^)(\\*|_)(?=\\S)(.+?)(?<=\\S)(\\2)`:
![image](https://user-images.githubusercontent.com/5613351/130227267-f8496707-54ec-456d-982c-6d4c670360c2.png)


Looks like order makes sense.

**Comment by gaebel** [comment]
The nesting order should not matter, I've made some [changes](https://github.com/bmoliveira/MarkdownKit/commit/761a30e8d5db9384d7bbaa9a5b83e6a7e8fd5443) to the regex, and the attribute inheritance.

**Comment by Mr-Sergey-K** [comment]
@gaebel Release this fix please
